---
ID: a31e2ede-0e97-462d-8ee2-43a277e62ba5
Parent: 04f6bbc4-099f-4103-8d99-b15c27695d69
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Oceanside/Components/Product/Categories/Parameters/Product Categories/Categories Section/Product Categories
DB: master
SharedFields:
- ID: 1eb8ae32-e190-44a6-968d-ed904c794ebf
  Hint: Source
  Value: datasource=/sitecore/Commerce/Catalog Management/Catalogs&allowmultipleselection=no&excludetemplatesforselection=Commerce Catalog Folder,Commerce Catalog&includetemplatesforselection=GeneralCategory
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  Hint: Type
  Value: Treelist
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160304T054302Z
