---
ID: f77512e7-f226-452d-afe8-e5818a58a137
Parent: f210cb32-084a-48f3-8dc9-a6692cd84a56
Template: f210cb32-084a-48f3-8dc9-a6692cd84a56
Path: /sitecore/templates/XcCommerce112Demo/Folders/Content Blocks/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160216T161100Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
