---
ID: 06c42dcc-abaa-4cf4-924d-95e33818dcdd
Parent: f50df7dd-c732-4838-a871-85c42ef5f77e
Template: 6d36df55-60e5-4591-899c-efccaf83579a
Path: /sitecore/templates/Rio Grande/Components/Marquee/Carousel Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T043751Z
