---
ID: ccb03503-be65-415b-bf9f-79ac8fa515bf
Parent: 2626bab4-7d86-4256-aa2d-6a2ef29fdb41
Template: 0437fee2-44c9-46a6-abe9-28858d9fee8c
Path: /sitecore/templates/CSDemo/Components/Product
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T170242Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
