---
ID: 75073bc8-0d13-4ea4-81d7-aaccc606c9fa
Parent: 1eac2bcf-d054-48f5-9e73-000c9f32c24d
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Rio Grande/Components/Product/Personalized Products/Personalized Products/Products
DB: master
SharedFields:
- ID: 1eb8ae32-e190-44a6-968d-ed904c794ebf
  Hint: Source
  Value: StartSearchLocation={4441D0B5-1080-4550-A91A-4C2C8245C986}&Filter=commercesearchitemtype:Product|parsedlanguage:english
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  Hint: Type
  Value: Multilist with Search
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160318T234144Z
