---
ID: 85917508-837b-4acd-b787-2219164ad1f5
Parent: e407afb5-a3a1-4356-8db1-8867c1f8da2e
Template: 2a3e91a0-7987-44b5-ab34-35c2d9de83b9
Path: /sitecore/layout/Renderings/CSDemo/Product/Product Sampler
DB: master
SharedFields:
- ID: 94069f66-609c-48b0-8281-521c30fb269d
  Hint: Open Properties after Add
  Value: -
- ID: ded9e431-3604-4921-a4b3-a6ec7636a5b6
  Hint: Controller Action
  Value: ProductSampler
- ID: e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7
  Hint: Controller
  Value: CSDemo.Controllers.ProductController, CSDemo
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20170512T222326Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\Admin
