---
ID: bdebe8d7-c888-456a-9c42-d6db7ab332fd
Parent: dfe6e26a-54ec-483b-8594-d6ac854b6e26
Template: 2a3e91a0-7987-44b5-ab34-35c2d9de83b9
Path: /sitecore/layout/Renderings/CSDemo/Product/Product Detail Without Availability
DB: master
SharedFields:
- ID: ded9e431-3604-4921-a4b3-a6ec7636a5b6
  Hint: Controller Action
  Value: ProductDetailNoAvailability
- ID: e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7
  Hint: Controller
  Value: Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160308T053533Z
