---
ID: d86c5baf-5c5f-4684-be04-a97b05057dc6
Parent: 3c937b2d-ea5e-4cb0-8fbd-1799bfa30475
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/CSDemo/Components/Tagging/Product Tag/Product Tag
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160315T205108Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
