---
ID: 3e52feae-159a-471e-a348-5d5e2b69aab6
Parent: dc84f551-d6ad-46b4-80b0-2ab72bb0a419
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/CSDemo/Base/Base Pages/Base PageMeta/Page Config
DB: master
SharedFields:
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160216T055051Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
