---
ID: a2e2a0f3-d048-44fb-a4dc-e2f8d97ab09c
Parent: d4c7f5f9-8977-4e0c-b6ce-28ae8e0753e2
Template: d4c7f5f9-8977-4e0c-b6ce-28ae8e0753e2
Path: /sitecore/client/Applications/Launchpad/PageSettings/Templates/LaunchPad-Button/__Standard Values
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20140702T095607
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
