---
ID: f8455ea4-effa-45ff-aaca-53bafa8fae08
Parent: c39b1cbd-2fec-4ba4-92c3-6c755ac45b38
Template: c39b1cbd-2fec-4ba4-92c3-6c755ac45b38
Path: /sitecore/templates/Oceanside/Components/Marquee/Carousel Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T043751Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
