---
ID: bd259e06-d2a3-46a0-a0c9-00bc1b74d3c1
Parent: 49b9f3e2-65cc-48f5-9a96-35efd0c752d8
Template: b3d2832f-2fbf-4466-9d95-d3a0c6476362
Path: /sitecore/content/Websites/Sites/XcCommerce112Demo/Home/ProductListing
DB: master
SharedFields:
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s" p:p="1">
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r uid="{F08043FB-EEA5-4A86-8648-26979958DCDE}" s:ds="" s:par="Section CSS Class=content%20products&amp;Container CSS Class=container&amp;Row CSS Class=row" />
        <r uid="{E7114DF6-060A-496E-84EB-EE203AF38E93}" p:after="r[@uid='{F08043FB-EEA5-4A86-8648-26979958DCDE}']" s:id="{FC71BBFA-44B6-4783-9812-604B08EF4AE4}" s:ph="row1" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160217T161039Z
    - ID: 3230cbc1-3e03-43ec-95ab-c6e1505de163
      Hint: Page Title
      Value: Category
    - ID: 4d027ffa-64cf-4502-8c87-f5195ff18d76
      Hint: Title
      Value: Category
    - ID: fbefdcf0-c9de-473a-aab7-e043d2e335ba
      Hint: Meta Description
      Value: Category Page
