---
ID: 10b43f1e-3e09-4c69-b3d0-c920496b7aee
Parent: 88473bc2-54ba-4282-ae4c-ae09f8c84b07
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/Rio Grande/Components/Tagging/Product Tag/Product Tag
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160315T205108Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
