---
ID: ec022971-028a-4654-afdd-a29c55ae079c
Parent: 441b60d3-09bb-4111-a3ad-d10076b78b54
Template: e55834fb-7c93-44a2-87c0-62beba282ced
Path: /sitecore/content/CSDemo/Home/Product catalog
DB: master
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  Hint: __Icon
  Value: Software/32x32/branch.png
- ID: 2882072b-e310-406b-8dd9-b22c9ea4a0f3
  Hint: CategoryDatasource
  Value: /sitecore/Commerce/Catalog Management/Catalogs/Adventure Works Catalog
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20141106T122951Z
