---
ID: a1dd90e1-602e-43fe-88a2-6e0872b49394
Parent: 3186710c-0229-4b9f-b48e-4e0e518e9d3e
Template: 3186710c-0229-4b9f-b48e-4e0e518e9d3e
Path: /sitecore/templates/CSDemo/Components/Product/Featured Categories/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160307T223637Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
