---
ID: 6da4c125-e3d5-4b30-8e1f-202038d2dbb2
Parent: 1af6ed60-6dec-4f36-a239-7deab79e1866
Template: 0b336c1e-b0f2-40fe-970f-bdb4810b7bfe
Path: /sitecore/templates/Rio Grande/Components/Page/Parameters/Column1 Config/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160217T091439Z
