---
ID: 46a4c4ef-d273-4a13-806a-91dd0dc6c04f
Parent: 17f73e15-2112-49a6-b044-141122eea8ee
Template: 81afaa32-f1b0-47de-a8e6-3e443a06510e
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/XCinemaDemo/Currency Configuration
DB: master
SharedFields:
- ID: f8abfa72-0fba-44a5-9122-cf11acb0ea61
  Hint: Currency Set
  Value: {4B494292-598E-4A61-A156-D7501F7953ED}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20161207T070315Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\Admin
