---
ID: d616068a-f8dc-4ad6-90bd-2bcce7298dd4
Parent: 17f73e15-2112-49a6-b044-141122eea8ee
Template: a2a80c92-826a-4928-beed-6e46fff31919
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/XCinemaDemo/Fulfillment Configuration
DB: master
SharedFields:
- ID: 0452eb98-bc28-4fd8-a3b4-533f26c62705
  Hint: Fulfillment Options
  Type: Multilist
  Value: {13372399-0C90-4827-B4DD-CA69B7EE3F94}
- ID: 769b63db-453f-44e6-aa90-cbc916e47f7d
  Hint: Allow items to be delivered Individually
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20161209T140442Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\Admin
