---
ID: 787dddf1-95f5-4e5a-8674-ca7c853595da
Parent: f2056122-4f5e-46dc-be2d-edd9c1961a83
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Oceanside/Components/Product/Personalized Products/Personalized Products/Products
DB: master
SharedFields:
- ID: 1eb8ae32-e190-44a6-968d-ed904c794ebf
  Hint: Source
  Value: StartSearchLocation={4441D0B5-1080-4550-A91A-4C2C8245C986}&Filter=commercesearchitemtype:Product|parsedlanguage:english
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  Hint: Type
  Value: Multilist with Search
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160318T234144Z
