---
ID: 67a36c49-b6f2-42eb-951d-f6fda044b6fa
Parent: 92c32e7e-861c-4508-bd98-f129528ee3a7
Template: 101ceb4d-e37c-49a0-883e-865ef4cd9216
Path: /sitecore/templates/Rio Grande/Components/Page/Parameters/Column3 Config/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160217T091556Z
