---
ID: 7f1ff02f-6a5d-4204-9f56-a367e5a73d13
Parent: efe85e42-04d5-41ba-b872-da6d365d505a
Template: 0437fee2-44c9-46a6-abe9-28858d9fee8c
Path: /sitecore/templates/Rio Grande/Components/Product/Categories/Parameters
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160304T053854Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
