---
ID: 9196ee6c-26da-451d-843a-af5b60195030
Parent: 8e8f49ee-655b-4b2d-8492-b1962e2e491f
Template: 2a3e91a0-7987-44b5-ab34-35c2d9de83b9
Path: /sitecore/layout/Renderings/CSDemo/Store/Product Instock Locations
DB: master
SharedFields:
- ID: ded9e431-3604-4921-a4b3-a6ec7636a5b6
  Hint: Controller Action
  Value: ProductInstockLocations
- ID: e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7
  Hint: Controller
  Value: CSDemo.Controllers.StoreController, CSDemo
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160512T005238Z
