---
ID: b9869121-afdb-4679-af7f-fc298ff2e355
Parent: be4190c6-f073-40b9-91e1-a32ece0179d8
Template: 3186710c-0229-4b9f-b48e-4e0e518e9d3e
Path: /sitecore/templates/Rio Grande/Components/Product/Featured Categories/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160307T223637Z
