---
ID: e01a6b72-8c71-47af-8584-c33a14d9e691
Parent: 1e0a97c2-92fc-4b41-ba84-901c8398fc9c
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Oceanside/Components/Product/Featured Products/Featured Products/Products
DB: master
SharedFields:
- ID: 1eb8ae32-e190-44a6-968d-ed904c794ebf
  Hint: Source
  Value: StartSearchLocation={08BFB57F-DAC9-4B11-90C5-5D19647899EF}&Filter=commercesearchitemtype:Product|parsedlanguage:english
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  Hint: Type
  Value: Multilist with Search
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T182159Z
