---
ID: a27cbeb7-2bc9-47f0-9736-a176a85a9fbc
Parent: 4337ffaf-99fc-40df-a655-cc1b0eabba3b
Template: 0a2a31a0-a3b8-493c-b5fe-1935e1723f52
Path: /sitecore/templates/Rio Grande/Components/Navigation/Mega Menu Navigation Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160304T210421Z
