---
ID: 4daee112-4db5-4a3b-902d-93413c8d50c6
Parent: 1a66caff-aab7-4d9a-84e5-397e379a13a6
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Rio Grande/Components/Product/Featured Products/Featured Products/Products
DB: master
SharedFields:
- ID: 1eb8ae32-e190-44a6-968d-ed904c794ebf
  Hint: Source
  Value: StartSearchLocation={DFDC60DB-C6C1-40BB-AAA1-7066D9D61F0B}&Filter=commercesearchitemtype:Product|parsedlanguage:english
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  Hint: Type
  Value: Multilist with Search
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T182159Z
