---
ID: d060115d-e390-41b3-8552-b4dfceb3bda8
Parent: bd259e06-d2a3-46a0-a0c9-00bc1b74d3c1
Template: b3d2832f-2fbf-4466-9d95-d3a0c6476362
Path: /sitecore/content/CSDemo/Home/Product Listing/Product Detail
DB: master
SharedFields:
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s" p:p="1">
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r uid="{75EDC8A6-0861-4DC4-B3DA-5151F8907E71}" p:after="r[@uid='{786ECE31-95BE-42A4-BD3B-7FC824D276EF}']" s:ds="" s:id="{E648F60A-676E-45CD-95AF-FAEEEC79E9AA}" s:par="" s:ph="page-body" />
        <r uid="{E5A6C541-E277-499D-9CB9-DFF8CE125A23}" p:after="r[@uid='{75EDC8A6-0861-4DC4-B3DA-5151F8907E71}']" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160217T214800Z
    - ID: 4d027ffa-64cf-4502-8c87-f5195ff18d76
      Hint: Page Title
      Value: ProductDetail
    - ID: fbefdcf0-c9de-473a-aab7-e043d2e335ba
      Hint: Meta Description
      Value: ProductDetail Page
