---
ID: a0dbe867-701d-4015-995a-c822266d2b43
Parent: 88473bc2-54ba-4282-ae4c-ae09f8c84b07
Template: 3c937b2d-ea5e-4cb0-8fbd-1799bfa30475
Path: /sitecore/templates/Rio Grande/Components/Tagging/Product Tag/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160315T205112Z
