---
ID: ecb5a98f-e26e-4782-89be-0968d08be3f3
Parent: 616e475c-c33c-4626-aba3-166976f4794b
Template: 338f84ba-3cdf-466e-8fb2-54ca845715d5
Path: /sitecore/templates/Rio Grande/Components/Navigation/Navigation Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160304T210417Z
